name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ソースコード取得
      uses: actions/checkout@v4

    - name: Python環境構築
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.*

    - name: pipenv導入
      run: |
        pip install pipenv
        
    - name: sphinxでビルド
      run: make html

    - name: GitHub Pagesの準備
      uses: actions/configure-pages@v5.0.0

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Path of the directory containing the static assets.
        path: build/html
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

              
